# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['zip_gui/app.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'sqlite3',
        'unittest',
        'pytest',
        'doctest',
        'curses',
        'xmlrpc',
        'pydoc',
        'PySide6.QtTest',
        'PySide6.QtNetwork',
        'PySide6.QtSql',
        'PySide6.QtXml', 'PySide6.QtXmlPatterns',
        'PySide6.QtMultimedia',
        'PySide6.QtOpenGL', 'PySide6.QtOpenGLWidgets',
        'PySide6.QtPrintSupport',
        'PySide6.QtWebEngineCore', 'PySide6.QtWebEngineWidgets',
        'PySide6.QtQml', 'PySide6.QtQuick',
        'PySide6.QtSvg',
        'PySide6.QtHelp',
        'PySide6.QtUiTools',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ZipGUI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='ZipGUI',
)
app = BUNDLE(
    coll,
    name='ZipGUI.app',
    icon=None,
    bundle_identifier=None,
)
